export const langData = {
	"PackageType": "Tipo di Pacchetto",
	"Categories": "Categorie",
	"GroupTour": "Giro di gruppo",
	"FixedTour": "Giro fisso",
	"OpenTour": "Giro aperto",
	"LocationWise": "Per quanto riguarda la posizione",
	"BudgetPerPerson": "Budget a persona",
	"MonthWise": "Mese saggio",
	"Clear": "Chiara",
	"BookNow": "Prenota ora",
	"EnquireNow": "Informarsi ora",
	"StartingFrom": "A partire da",
	"Location": "Posizione",
	"Package": "Pacchetto",
	"HideInfo": "Nascondi informazioni",
	"MoreInfo": "Ulteriori informazioni",
	"Showing": "Mostrando",
	"PackagesForYou": "Pacchetti per te",
	"SortByPrice": "Ordina per prezzo",
	"LowToHigh": "Dal basso all'alto",
	"HighToLow": "Dall'alto al basso",
	"DownloadItinerary": "Scarica Itinerario",
	"ShareItOn": "Condividilo",
	"TripDate": "Data del viaggio",
	"SelectTravellers": "Seleziona Viaggiatori",
	"TotalPrice": "Prezzo totale",
	"BookingPrice": "Prezzo di prenotazione",
	"Activities": "Attività",
	"Overview": "Panoramica",
	"ReadLess": "Leggi di meno",
	"ReadMore": "Per saperne di più",
	"Itinerary": "Itinerario",
	"Accommodation": "Alloggio",
	"Review": "Revisione",
	"PackageItinerary": "Itinerario del pacchetto",
	"ServicesIncluded": "Servizi Inclusi",
	"Policy": "Politica",
	"Inclusions": "Inclusioni",
	"Exclusions": "Esclusioni",
	"PaymentPolicy": "Politica di pagamento",
	"CancellationPolicy": "Politica di cancellazione",
	"TermsAndConditions": "Termini e Condizioni",
	"FAQsAbout": "Domande frequenti su",
	"Share": "Condividere",
	"Tweet": "Twitta",
	"Whatsapp": "WhatsApp",
	"YourPreference": "La tua preferenza",
	"ViewAll": "Mostra tutto",
	"SimilarPackages": "Pacchetti simili",
	"MoreTripsDeparture": "Più Viaggi Partenza",
	"SimilarBlogs": "Blog simili",
	"Author": "Autrice",
	"Date": "Data",
	"ExploreGreatDeals": "Esplora fantastiche offerte",
	"ContactUs": "Contattaci",
	"WriteATestimonial": "Scrivi una testimonianza",
	"Testimonials": "Testimonianze",
	"Home": "Casa",
	"Add": "Aggiungere",
	"Title": "Titolo",
	"SelectTitle": "Seleziona Titolo",
	"Name": "Nome",
	"CompanyName": "Nome della ditta",
	"PositionInCompany": "Ruolo aziendale",
	"Website": "Sito web",
	"Content": "Contenuto",
	"Submit": "Invia",
	"ChatWhatsapp": "Chatta Whatsapp",
	"DirectCall": "Chiamata diretta",
	"WRITE": "SCRIVERE",
	"YOURTESTIMONIAL": "LA TUA TESTIMONIANZA",
	"SimilarTestimonials": "Testimonianze simili",
	"PlacesToVisitIn": "Luoghi da visitare",
	"About": "Di",
	"PhotoGallery": "Galleria fotografica",
	"Gallery": "Galleria",
	"Blogs&News": "Blog e notizie",
	"ThankYouForContactingUs": "Grazie per averci contattato",
	"GoToHome": "Vai a casa",
	"EnquireThisTrip": "Richiedi questo viaggio",
	"Back": "Indietro",
	"Destinations": "Destinazioni",

	// Pradeepk(Add Language english to italian)
	"ViewDetail": "Vedi Dettagli",
	"Copyright": "Diritto d'autore",
	"DesignBy": "Disegnato da",
	"Indiainternets": "Indiainternet",
	"PerPerson": "A testa",
	"From": "Da",
	"NumberofPersons": "Numero di persone",
	"Apply": "Fare domanda a",
	"CheckAvailability": "Verificare la disponibilità",
	"Pleaseselecttheslot": "Seleziona lo slot",
	"Note*": "Nota*",
	"Morethan6personspleasecontact": "Più di 6 persone da contattare",
	"SelecttheDateofTravel": "Seleziona la data del viaggio",
	"ThePriceInCalendarRepresentTheStartingPricePerPerson": "Il prezzo nel calendario rappresenta il prezzo di partenza A testa",

}