<?php
if(env('CAB_VERSION')==2) {
    $cab_route_types = [
        '1'=>'INTERCITY TRIP',
        '2'=>'OUTSTATION',
        '3'=>'AIRPORT',
        '4'=>'RAILWAYS',
        '5'=>'SIGHTSEEING',
    ];
} else {
    $cab_route_types = [
        '0'=>'Transfer',
        '1'=>'Round-Trip',
        '2'=>'Sightseeing',
        '3'=>'Airport',
    ];    
}

return [
    'ADMIN_ROUTE_NAME' => 'admin',

    'order_prefix' => 'YPL',

    'img_extension' => ['jpg', 'jpeg', 'gif', 'png', 'JPG', 'JPEG', 'GIF', 'PNG'],

    'compare_scope' => [
        '=' => '=',
        '>' => '>',
        '<' => '<',
        '>=' => '>=',
        '<=' => '<='
    ],

    'currency_arr' => [
        '1' => 'USD',
        '2' => 'EUR',
        '3' => 'INR',
        '4' => 'AUD',
        '5' => 'GBP'
    ],

    'currency_symbol_arr' => [
        '1' => "&#36;",
        '2' => "&#128;",
        '3' => "&#x20B9;",
        '4' => "A&#36;",
        '5' => "&#163;"
    ],

    'device_types_arr' => [
        'desktop' => "Desktop",
        'mobile' => "Mobile"
    ],

    'input_types_arr' => [
        'text' => 'Text',
        'textarea' => 'Textarea',
        'checkbox' => 'Checkbox',
        'radio' => 'Radio',
        'file' => 'File',
        'email' => 'Email',
    ],

    'setting_types_arr' => [
        'website' => 'Website',
        'seo' => 'SEO',
        //'social_links' => 'Social Links',
    ],

    'order_type' => [
        '1' => 'Package',
        '2' => 'Pay-Online',
        '3' => 'Flight',
        '4' => 'Cab',
        '5' => 'Hotel',
        '6' => 'Activity',
        '7' => 'Wallet Recharge',
        '8' => 'Rental'
    ],

    'blog_type_arr' => [
        'blogs' => 'Blogs',
        'news' => 'News',
    ],

    'months_arr' => [
        '1' => 'January',
        '2' => 'February',
        '3' => 'March',
        '4' => 'April',
        '5' => 'May',
        '6' => 'June',
        '7' => 'July',
        '8' => 'August',
        '9' => 'September',
        '10' => 'October',
        '11' => 'November',
        '12' => 'December',
    ],

    'days_arr' => [
        'sunday' => 'Sunday',
        'monday' => 'Monday',
        'tuesday' => 'Tuesday',
        'wednesday' => 'Wednesday',
        'thursday' => 'Thursday',
        'friday' => 'Friday',
        'saturday' => 'Saturday',
    ],

    'activity_level_arr' => [
        '1' => 'Light',
        '2' => 'Moderate',
        '3' => 'Strenuous',
        '4' => 'Extreme/Difficult',
    ],

    'module_level_arr' => [
        'accommodations' => 'Accommodations',
        'destinations' => 'Destinations',
        'packages'  => 'Packages'
    ],

    'service_level_arr' => [
        '1' => 'Standard',
        '2' => 'Deluxe',
        '3' => 'Premium',
        '4' => 'Superior',
    ],

    'fixed_service_level_arr' => [
        '1','2','3','4'
    ],

    'menu_link_type_arr' => [
        'internal' => 'Internal',
        'external' => 'External',
        'category' => 'Category',
        'destination' => 'Destination',
        'faq_category' => 'Faq Category',
        'blog' => 'Blog',
        'news' => 'News',
        'cms' => 'CMS Page',
        'modules' => 'Modules',
        'tour_category' => 'Tour Category',
    ],

    'enq_for_types' => [
        '1'=>'Package',
        '2'=>'Accomodation',
        '3'=>'Flight',
        '4'=>'Activity',
        '5'=>'Other',
        '6'=>'Cab',
        '7'=>'Rental',
    ],

    'enq_status' => [
        '1'=>'New',
    ],
    'range_filters' => [
        'custom' => 'Custom',
        'yesterday' => 'Yesterday',
        'today' => 'Today',
        'tomorrow' => 'Tomorrow',
        'this_week' => 'This Week',
        'next_week' => 'Next Week',
        'last_week' => 'Last Week',
        'this_month' => 'This Month',
        'last_month' => 'Last Month',
        'last_7_days' => 'Last 7 days',
        'last_30_days' => 'Last 30 days',
        'this_year' => 'Current Year',
        'last_year' => 'Previous Year',
    ],
    'seo_module_config_arr' => [
        'default' => 'Default',
        'home' => 'Home',
        'thank_you' => 'Thank You',
        'pay_online' => 'Pay Online',
        'contact_us' => 'Contact Us',
        'tour_category' => 'Tour Category Listing',
        'package_listing' => 'Packages',
        'destination_listing' => 'Destination Listing',
        'hotel_listing' => 'Hotels',
        'activity_listing' => 'Activities',
        'blog_listing' => 'Blog Listing',
        'news_listing' => 'News Listing',
        'testimonial_listing' => 'Testimonial Listing',
        'team_listing' => 'Team Listing',
        'cms_listing' => 'CMS Listing',
        'agentuser' => 'Agent user',
        'flight' => 'Flight',
        'cab' => 'Cab',
        'rental' => 'Rental',
        'customer' => 'customer',
        'vendor' => 'Vendor',
    ],
    'meal_options' => [
        'Breakfast'=>'Breakfast',
        'Lunch'=>'Lunch',
        'Dinner'=>'Dinner',
        'Lunch or Dinner'=>'Lunch or Dinner',
        'Snacks'=>'Snacks',
    ],
    'lead_status_category_arr' => [
        'new' => 'New',
        'open' => 'Open',
        'in_process' => 'In-Process',
        'closed' => 'Closed',
    ],
    'theme_name' => env('THEME','default'),
    'themejs' => env('THEME','default').'/',
    'theme' => 'themes.'.env('THEME','overlandescape'),
    'assets' => 'assets/'.env('THEME','overlandescape'),

    'enquiry_mapping' => [
        'name' => 'Name',
        'phone' => 'Phone',
        'email' => 'Email',
        'destination' => 'Destination',
        'package' => 'Package',
        'accommodation' => 'Accommodation',
        'meal_plans' => 'Meal Plan',
        'activity' => 'Activity',
        'date_of_travel' => 'Date of Travel',
        'duration' => 'Duration',
        'no_of_days' => 'No. of Days',
        'no_of_pax' => 'No. of Persons',
        'adu_abo_12' => 'Adults - Above 12 years',
        'chi_6_12' => 'Children - 6-12 years',
        'chi_2_5' => 'Children - 2-5 years',
        'infants_upto_2' => 'Infants - Upto 2 years',
        'content' => 'Comment'
    ],
    'bookings_per_month' => [
        '0_5' => '0 - 5',
        '5_15' => '5 - 15',
        '15_25' => '15 - 25',
        'more_than_25' => 'More than 25',
    ],
    'no_of_employees' => [
        'less_than_5_employees' => 'Less than 5 employees',
        '5_10_employees' => '5 - 10 employees',
        '10_15_employees' => '10 - 15 employees',
        'more_than_15' => 'More than 15',
    ],
    'agency_durations' => [
        'less_than_2_years_old' => 'Less than 2 years old',
        '2_5_years_old' => '2 - 5 years old',
        '5_10_years_old' => '5 - 10 years old',
        'more_than_10_years_old' => 'More than 10 years old',
    ],
    'traveler_regions' => [
        'us' => 'US',
        'uk' => 'UK',
        'rest_of_europe' => 'Rest of Europe',
        'middle_east' => 'Middle East',
        'india' => 'India',
        'asia' => 'Asia',
    ],
    'source_types' => [
        'emails_from_us' => 'Emails from us',
        'we_called_you' => 'We called you',
        'google_bing_search' => 'Google / Bing search',
        'news_magazines' => 'News/ Magazines',
        'linkedin_facebook' => 'LinkedIn / Facebook',
        'other_travel_agents' => 'Other Travel Agents',
        'your_team_member' => 'Your team member',
        'other_misc' => 'Other / Misc'
    ],
    'cab_route_types' => $cab_route_types,
    'tripTimeArr'  =>[
            "00:00" =>"12:00 AM",
            "00:15" =>"12:15 AM",
            "00:30" =>"12:30 AM",
            "00:45" =>"12:45 AM",
            "01:00" =>"01:00 AM",
            "01:15" =>"01:15 AM",
            "01:30" =>"01:30 AM",
            "01:45" =>"01:45 AM",
            "02:00" =>"02:00 AM",
            "02:15" =>"02:15 AM",
            "02:30" =>"02:30 AM",
            "02:45" =>"02:45 AM",
            "03:00" =>"03:00 AM",
            "03:15" =>"03:15 AM",
            "03:30" =>"03:30 AM",
            "03:45" =>"03:45 AM",
            "04:00" =>"04:00 AM",
            "04:15" =>"04:15 AM",
            "04:30" =>"04:30 AM",
            "04:45" =>"04:45 AM",
            "05:00" =>"05:00 AM",
            "05:15" =>"05:15 AM",
            "05:30" =>"05:30 AM",
            "05:45" =>"05:45 AM",
            "06:00" =>"06:00 AM",
            "06:15" =>"06:15 AM",
            "06:30" =>"06:30 AM",
            "06:45" =>"06:45 AM",
            "07:00" =>"07:00 AM",
            "07:15" =>"07:15 AM",
            "07:30" =>"07:30 AM",
            "07:45" =>"07:45 AM",
            "08:00" =>"08:00 AM",
            "08:15" =>"08:15 AM",
            "08:30" =>"08:30 AM",
            "08:45" =>"08:45 AM",
            "09:00" =>"09:00 AM",
            "09:15" =>"09:15 AM",
            "09:30" =>"09:30 AM",
            "09:45" =>"09:45 AM",
            "10:00" =>"10:00 AM",
            "10:15" =>"10:15 AM",
            "10:30" =>"10:30 AM",
            "10:45" =>"10:45 AM",
            "11:00" =>"11:00 AM",
            "11:15" =>"11:15 AM",
            "11:30" =>"11:30 AM",
            "11:45" =>"11:45 AM",
            "12:00" =>"12:00 PM",
            "12:15" =>"12:15 PM",
            "12:30" =>"12:30 PM",
            "12:45" =>"12:45 PM",
            "13:00" =>"01:00 PM",
            "13:15" =>"01:15 PM",
            "13:30" =>"01:30 PM",
            "13:45" =>"01:45 PM",
            "14:00" =>"02:00 PM",
            "14:15" =>"02:15 PM",
            "14:30" =>"02:30 PM",
            "14:45" =>"02:45 PM",
            "15:00" =>"03:00 PM",
            "15:15" =>"03:15 PM",
            "15:30" =>"03:30 PM",
            "15:45" =>"03:45 PM",
            "16:00" =>"04:00 PM",
            "16:15" =>"04:15 PM",
            "16:30" =>"04:30 PM",
            "16:45" =>"04:45 PM",
            "17:00" =>"05:00 PM",
            "17:15" =>"05:15 PM",
            "17:30" =>"05:30 PM",
            "17:45" =>"05:45 PM",
            "18:00" =>"06:00 PM",
            "18:15" =>"06:15 PM",
            "18:30" =>"06:30 PM",
            "18:45" =>"06:45 PM",
            "19:00" =>"07:00 PM",
            "19:15" =>"07:15 PM",
            "19:30" =>"07:30 PM",
            "19:45" =>"07:45 PM",
            "20:00" =>"08:00 PM",
            "20:15" =>"08:15 PM",
            "20:30" =>"08:30 PM",
            "20:45" =>"08:45 PM",
            "21:00" =>"09:00 PM",
            "21:15" =>"09:15 PM",
            "21:30" =>"09:30 PM",
            "21:45" =>"09:45 PM",
            "22:00" =>"10:00 PM",
            "22:15" =>"10:15 PM",
            "22:30" =>"10:30 PM",
            "22:45" =>"10:45 PM",
            "23:00" =>"11:00 PM",
            "23:15" =>"11:15 PM",
            "23:30" =>"11:30 PM",
            "23:45" =>"11:45 PM",

    ],
    'months_it'  =>[
        'Jan' => 'Gen',
        'Feb' => 'Feb',
        'Mar' => 'Mar',
        'Apr' => 'Apr',
        'May' => 'Mag',
        'Jun' => 'Giu',
        'Jul' => 'Lug',
        'Aug' => 'Ago',
        'Sep' => 'Set',
        'Oct' => 'Ott',
        'Nov' => 'Nov',
        'Dec' => 'Dic',
    ],
    'meal_types' => [
        'accommodation_only' => 'Only Room',
        'breakfast' => 'Bed and Breakfast',
        'breakfast_dinner' => 'Breakfast and Dinner',
        'breakfast_lunch_dinner' => 'Breakfast, Lunch and Dinner',

    ],
    'name_title_arr' => [
        'Mr' => 'Mr.',
        'Mrs' => 'Mrs.'
    ],
    'plan_includes' => [
        '1' => 'Free Cancellation',
        '2' => '10 % Discount',
        '3' => 'Free Breakfast',
        '4' => 'No Meal',
        '5' => 'Free Wifi',
    ],
    'room_views' => [
        '1'=>'No View',
        '2'=>'Sea View',
        '3'=>'Valley View',
        '4'=>'Hill View',
        '5'=>'Pool View',
        '6'=>'Garden View',
        '7'=>'River View',
        '8'=>'Lake View',
        '9'=>'Palace View',
        '10'=>'Bay View',
        '11'=>'Jungle View',
        '12'=>'City View',
        '13'=>'Landmark View',
        '14'=>'Terrace View',
        '15'=>'Courtyard View',
        '16'=>'Desert View',
        '17'=>'Golf Course View',
        '18'=>'Mountain View',
        '19'=>'Ocean View',
        '20'=>'Marina View',
        '21'=>'Backwater View',
        '22'=>'Resort View',
        '23'=>'Monument View',
        '24'=>'Park View',
        '25'=>'Lagoon View',
        '26'=>'Forest View',
        '27'=>'Airport View',
        '28'=>'Countryside View',
        '29'=>'Harbor View',
        '30'=>'Inter-coastal View',
    ],
    'bed_types' => [
        '1'=>'Twin Bed',
        '2'=>'King Bed',
        '3'=>'Queen Bed',
        '4'=>'Double Bed',
        '5'=>'Single Bed',
        '6'=>'Sofa Bed',
    ],
    'extra_bed_types' => [
        '1'=>'No Extra Bed',              
        '2'=>'Mattress',              
        '3'=>'Cot',              
        '4'=>'Sofa cum bed',              
    ],
    'flight_cancellation_reasons' => [
        'no_show' => 'No Show - Refund expected in 30 to 45 working days',
        'already_cancelled_with_airline' => 'Already Cancelled with Airline - Refund expected in 24 hours',
        'flight_delay_or_cancelled' => 'Flight Delay or Cancelled - (Please fax us a Endorsement copy duly authorized by the respective ariline at {manager_phone} or mail to {manager_email}) - Refund expected in 2 days',
        'rescheduled_ticket_cancellation' => 'Rescheduled ticket cancellation - (If you have earlier rescheduled this ticket directly with the airline, please Provide us with the new ticket number) - Refund expected in 30 to 45 working days.',
        'physical_ticket' => 'Physical Ticket - (Please Courier us the tickets) - Refund in 24 hours after receiving the ticket',
        'general_normal_cancellation' => 'General/Normal Cancellation - Refund expected in 24 hours',
        'other' => 'Other - ',
    ],

    'order_status_category_arr' => [
        'new' => 'New',
        'confirmed' => 'Confirmed',
        'processing' => 'Processing',
        'cancelled' => 'Cancelled',
    ],

    'payment_status_arr' => [
        '0'=>'Unpaid',
        '1'=>'Paid',
        '2'=>'Failed',
        '3'=>'Refunded',
        '4'=>'Debit',
    ],
    
    'rental_type_arr' => [
        '1' => 'Motorcycle',
        '2' => 'Scooter',
    ],
    'activity_duration_type_arr' => [
        '2' => 'Days',
        '3' => 'Hours',
        '1' => 'Minutes',
        '4' => 'Kilometer',
        '5' => 'LAP',
    ],

    'SESSION_LIFETIME'=> env('SESSION_LIFETIME',120),
    'MAIL_FROM_ADDRESS'=> env('MAIL_FROM_ADDRESS',''),
    'CACHE_DRIVER'=> env('CACHE_DRIVER',''),
    'SENTRY_JS_DSN'=> env('SENTRY_JS_DSN',''),
    'CAB_VERSION'=> env('CAB_VERSION',1),

    'flight_class_arr' => [
        'Premium Economy' => 'Premium Economy',
        'Business' => 'Business',
        'First' => 'First',
        'Economy' => 'Economy'
    ],
    'flight_stops_arr' => [
        '0' => 'Non-Stop',
        '1' => '1-Stop',
        '2' => '2-Stop(s)',
        '3' => '3-Stop(s)',
        '4' => '4-Stop(s)'
    ],
    'flight_available_for_arr' => [
        'all_agent' => 'For All Agent only',
        'all_customer' => 'For All Customer Only',
        'all_customer_agent' => 'For All Customer & Agents',
        'p_agents' => 'For particular Agents',
    ],
    'agent_flight_available_for_arr' => [
        'all_agent' => 'For All Agent only',
        'all_customer' => 'For All Customer Only',
        'all_customer_agent' => 'For All Customer & Agents',
    ],
];